<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit52fb2c591c9c54f25ee3cba4438bdc1c
{
    public static $files = array (
        'd767e4fc2dc52fe66584ab8c6684783e' => __DIR__ . '/..' . '/adbario/php-dot-notation/src/helpers.php',
    );

    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'Adbar\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Adbar\\' => 
        array (
            0 => __DIR__ . '/..' . '/adbario/php-dot-notation/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit52fb2c591c9c54f25ee3cba4438bdc1c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit52fb2c591c9c54f25ee3cba4438bdc1c::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
